import type { ConversationLanguage } from "./types";

type UiKey = "panelTitle" | "clearMemory" | "ready" | "connecting" | "thinking" | "speechProcessing" | "ttsOn" | "ttsOff" | "ttsToggle" | "ttsUnsupported" | "startVoice" | "stopVoice" | "speakCommand" | "voiceUnsupported" | "sendCommand" | "welcome" | "trySaying" | "saleSuggestion" | "restockSuggestion" | "expenseSuggestion" | "inputPlaceholder" | "voiceInput" | "shopData" | "confirmRequired" | "enter" | "edit" | "notNow" | "confirmSave" | "confidenceWarning" | "saved" | "saveFailed" | "couldNotComplete" | "languageLabel" | "openingStock" | "lossAtCost" | "total" | "yourAssistant" | "parserRules" | "parserLlm" | "parserFallback" | "voiceConfirm" | "voiceConfirmListening" | "voiceConfirmUnavailable" | "voiceConfirmHint" | "readbackIntro" | "readbackQuestion";

const ui: Record<ConversationLanguage, Record<UiKey, string>> = {
  en: { panelTitle: "Ask Dukaandaar", clearMemory: "Clear short-term memory", ready: "Ready to help", welcome: "Namaste! Tell me what happened at the shop, or ask about sales, purchases, stock and expenses.", trySaying: "Try saying", saleSuggestion: "Sold 5 Maggi at ₹14 each", restockSuggestion: "What should I restock?", expenseSuggestion: "Paid ₹350 for electricity", inputPlaceholder: "Type or say what happened…", voiceInput: "Voice input", shopData: "Shop data stays here", confirmRequired: "Confirmations required before any write", enter: "Enter ↵", edit: "Edit", notNow: "Not now", confirmSave: "Confirm & save", confidenceWarning: "Please check the details carefully.", saved: "Saved to your shop ledger", saveFailed: "Save failed", couldNotComplete: "Could not complete", languageLabel: "Conversation language", openingStock: "Opening stock", lossAtCost: "Loss at cost", total: "Total", yourAssistant: "Your shop assistant", connecting: "Connecting", thinking: "Thinking through that…", speechProcessing: "Transcribing your recording…", ttsOn: "Turn spoken replies on", ttsOff: "Turn spoken replies off", ttsToggle: "Toggle spoken replies", ttsUnsupported: "Speech output is not supported", startVoice: "Start voice input", stopVoice: "Stop listening", speakCommand: "Speak a command", voiceUnsupported: "Voice input requires Chrome or Edge", sendCommand: "Send command", parserRules: "Rules parser · confidence {confidence}%", parserLlm: "LLM provider: {provider} · confidence {confidence}%", parserFallback: "Rules fallback · requested provider: {provider} · confidence {confidence}%", voiceConfirm: "Confirm by voice", voiceConfirmListening: "Listening… say yes to save", voiceConfirmUnavailable: "Voice confirmation is unavailable in this browser", voiceConfirmHint: "I did not hear a clear confirmation. Say “yes” to save or use the buttons.", readbackIntro: "I understood:", readbackQuestion: "Is that correct?" },
  hi: { panelTitle: "दुकान सहायक", clearMemory: "अल्पकालिक याददाश्त साफ़ करें", ready: "मदद के लिए तैयार", welcome: "नमस्ते! दुकान में क्या हुआ बताइए, या बिक्री, खरीद, स्टॉक और खर्च के बारे में पूछिए।", trySaying: "ऐसा कहें", saleSuggestion: "5 मैगी ₹14 प्रति पीस में बेचे", restockSuggestion: "क्या दोबारा मंगाना चाहिए?", expenseSuggestion: "बिजली के ₹350 दिए", inputPlaceholder: "लिखें या बोलें…", voiceInput: "आवाज़ से इनपुट", shopData: "दुकान का डेटा यहीं रहता है", confirmRequired: "हर बदलाव से पहले पुष्टि ज़रूरी है", enter: "Enter ↵", edit: "बदलें", notNow: "अभी नहीं", confirmSave: "पुष्टि करें और सेव करें", confidenceWarning: "कृपया विवरण ध्यान से जाँचें।", saved: "दुकान के खाते में सेव हुआ", saveFailed: "सेव नहीं हुआ", couldNotComplete: "पूरा नहीं हो सका", languageLabel: "बातचीत की भाषा", openingStock: "शुरुआती स्टॉक", lossAtCost: "लागत पर नुकसान", total: "कुल", yourAssistant: "आपका दुकान सहायक", connecting: "कनेक्ट हो रहा है", thinking: "सोच रहा हूँ…", speechProcessing: "आपकी रिकॉर्डिंग का प्रतिलेखन हो रहा है…", ttsOn: "बोले गए जवाब चालू करें", ttsOff: "बोले गए जवाब बंद करें", ttsToggle: "बोले गए जवाब बदलें", ttsUnsupported: "ध्वनि आउटपुट समर्थित नहीं है", startVoice: "आवाज़ से बोलना शुरू करें", stopVoice: "सुनना बंद करें", speakCommand: "आदेश बोलें", voiceUnsupported: "आवाज़ इनपुट के लिए Chrome या Edge चाहिए", sendCommand: "आदेश भेजें", parserRules: "नियम पार्सर · विश्वास {confidence}%", parserLlm: "LLM प्रदाता: {provider} · विश्वास {confidence}%", parserFallback: "नियम फ़ॉलबैक · अनुरोधित प्रदाता: {provider} · विश्वास {confidence}%", voiceConfirm: "आवाज़ से पुष्टि", voiceConfirmListening: "सुन रहा हूँ… सेव करने के लिए हाँ कहें", voiceConfirmUnavailable: "इस ब्राउज़र में आवाज़ से पुष्टि उपलब्ध नहीं है", voiceConfirmHint: "स्पष्ट पुष्टि सुनाई नहीं दी। सेव करने के लिए “हाँ” कहें या बटन इस्तेमाल करें।", readbackIntro: "मैंने यह समझा:", readbackQuestion: "क्या यह सही है?" },
  bn: { panelTitle: "দোকানের সহকারী", clearMemory: "স্বল্পমেয়াদি স্মৃতি মুছুন", ready: "সাহায্যের জন্য প্রস্তুত", welcome: "নমস্কার! দোকানে কী হয়েছে বলুন, অথবা বিক্রি, কেনাকাটা, মজুত ও খরচ সম্পর্কে জিজ্ঞাসা করুন।", trySaying: "এভাবে বলুন", saleSuggestion: "৫টি ম্যাগি ₹১৪ করে বিক্রি হয়েছে", restockSuggestion: "কী কী আবার অর্ডার করব?", expenseSuggestion: "বিদ্যুতের জন্য ₹৩৫০ দিয়েছি", inputPlaceholder: "লিখুন বা বলুন…", voiceInput: "কথার ইনপুট", shopData: "দোকানের তথ্য এখানেই থাকে", confirmRequired: "কোনো পরিবর্তনের আগে নিশ্চিত করতে হবে", enter: "Enter ↵", edit: "সম্পাদনা", notNow: "এখন নয়", confirmSave: "নিশ্চিত করে সংরক্ষণ করুন", confidenceWarning: "তথ্যগুলো ভালো করে দেখে নিন।", saved: "দোকানের খাতায় সংরক্ষিত", saveFailed: "সংরক্ষণ হয়নি", couldNotComplete: "সম্পন্ন করা যায়নি", languageLabel: "কথোপকথনের ভাষা", openingStock: "শুরুর মজুত", lossAtCost: "ক্রয়মূল্যে ক্ষতি", total: "মোট", yourAssistant: "আপনার দোকানের সহকারী", connecting: "সংযোগ করা হচ্ছে", thinking: "বুঝে নিচ্ছি…", speechProcessing: "আপনার রেকর্ডিং ট্রান্সক্রাইব করা হচ্ছে…", ttsOn: "কথায় উত্তর চালু করুন", ttsOff: "কথায় উত্তর বন্ধ করুন", ttsToggle: "কথায় উত্তর চালু বা বন্ধ করুন", ttsUnsupported: "কণ্ঠস্বর আউটপুট সমর্থিত নয়", startVoice: "কথা বলা শুরু করুন", stopVoice: "শোনা বন্ধ করুন", speakCommand: "একটি নির্দেশ বলুন", voiceUnsupported: "ভয়েস ইনপুটের জন্য Chrome বা Edge দরকার", sendCommand: "নির্দেশ পাঠান", parserRules: "নিয়ম পার্সার · আস্থার স্কোর {confidence}%", parserLlm: "LLM প্রদানকারী: {provider} · আস্থার স্কোর {confidence}%", parserFallback: "নিয়মে ফলব্যাক · অনুরোধ করা প্রদানকারী: {provider} · আস্থার স্কোর {confidence}%", voiceConfirm: "কথা বলে নিশ্চিত করুন", voiceConfirmListening: "শুনছি… সংরক্ষণ করতে হ্যাঁ বলুন", voiceConfirmUnavailable: "এই ব্রাউজারে কথায় নিশ্চিত করা যায় না", voiceConfirmHint: "স্পষ্ট সম্মতি শুনতে পাইনি। সংরক্ষণ করতে “হ্যাঁ” বলুন বা বোতাম ব্যবহার করুন।", readbackIntro: "আমি বুঝেছি:", readbackQuestion: "এটাই কি ঠিক?" },
  fr: { panelTitle: "Parler à Dukaandaar", clearMemory: "Effacer la mémoire temporaire", ready: "Prêt à vous aider", welcome: "Bonjour ! Dites-moi ce qui s'est passé à la boutique, ou posez une question sur les ventes, achats, stocks et dépenses.", trySaying: "Essayez de dire", saleSuggestion: "Vendu 5 Maggi à 14 ₹ pièce", restockSuggestion: "Que dois-je réapprovisionner ?", expenseSuggestion: "Payé 350 ₹ d'électricité", inputPlaceholder: "Écrivez ou dites ce qui s'est passé…", voiceInput: "Commande vocale", shopData: "Les données restent dans la boutique", confirmRequired: "Confirmation requise avant toute écriture", enter: "Entrée ↵", edit: "Modifier", notNow: "Pas maintenant", confirmSave: "Confirmer et enregistrer", confidenceWarning: "Vérifiez attentivement les détails.", saved: "Enregistré dans le registre", saveFailed: "Échec de l'enregistrement", couldNotComplete: "Impossible de terminer", languageLabel: "Langue de conversation", openingStock: "Stock initial", lossAtCost: "Perte au coût d'achat", total: "Total", yourAssistant: "Votre assistant de boutique", connecting: "Connexion en cours", thinking: "Je réfléchis…", speechProcessing: "Transcription de votre enregistrement…", ttsOn: "Activer les réponses vocales", ttsOff: "Désactiver les réponses vocales", ttsToggle: "Basculer les réponses vocales", ttsUnsupported: "La sortie vocale n’est pas prise en charge", startVoice: "Démarrer la saisie vocale", stopVoice: "Arrêter l’écoute", speakCommand: "Dicter une commande", voiceUnsupported: "La saisie vocale nécessite Chrome ou Edge", sendCommand: "Envoyer la commande", parserRules: "Analyseur à règles · confiance {confidence} %", parserLlm: "Fournisseur LLM : {provider} · confiance {confidence} %", parserFallback: "Retour aux règles · fournisseur demandé : {provider} · confiance {confidence} %", voiceConfirm: "Confirmer par la voix", voiceConfirmListening: "Écoute… dites oui pour enregistrer", voiceConfirmUnavailable: "La confirmation vocale est indisponible dans ce navigateur", voiceConfirmHint: "Je n’ai pas entendu de confirmation claire. Dites « oui » ou utilisez les boutons.", readbackIntro: "J’ai compris :", readbackQuestion: "Est-ce exact ?" },
  es: { panelTitle: "Preguntar a Dukaandaar", clearMemory: "Borrar la memoria temporal", ready: "Listo para ayudarte", welcome: "¡Hola! Cuéntame qué pasó en la tienda o pregunta por ventas, compras, stock y gastos.", trySaying: "Prueba a decir", saleSuggestion: "Vendí 5 Maggi a 14 ₹ cada uno", restockSuggestion: "¿Qué debo reponer?", expenseSuggestion: "Pagué 350 ₹ de electricidad", inputPlaceholder: "Escribe o di lo que pasó…", voiceInput: "Entrada de voz", shopData: "Los datos de la tienda se quedan aquí", confirmRequired: "Confirma antes de guardar cualquier cambio", enter: "Intro ↵", edit: "Editar", notNow: "Ahora no", confirmSave: "Confirmar y guardar", confidenceWarning: "Revisa los detalles con atención.", saved: "Guardado en el registro", saveFailed: "Error al guardar", couldNotComplete: "No se pudo completar", languageLabel: "Idioma de conversación", openingStock: "Stock inicial", lossAtCost: "Pérdida al coste", total: "Total", yourAssistant: "Tu asistente de tienda", connecting: "Conectando", thinking: "Pensando…", speechProcessing: "Transcribiendo tu grabación…", ttsOn: "Activar respuestas habladas", ttsOff: "Desactivar respuestas habladas", ttsToggle: "Alternar respuestas habladas", ttsUnsupported: "La salida de voz no es compatible", startVoice: "Iniciar entrada de voz", stopVoice: "Dejar de escuchar", speakCommand: "Di un comando", voiceUnsupported: "La entrada de voz requiere Chrome o Edge", sendCommand: "Enviar comando", parserRules: "Analizador por reglas · confianza {confidence} %", parserLlm: "Proveedor LLM: {provider} · confianza {confidence} %", parserFallback: "Respaldo con reglas · proveedor solicitado: {provider} · confianza {confidence} %", voiceConfirm: "Confirmar por voz", voiceConfirmListening: "Escuchando… di sí para guardar", voiceConfirmUnavailable: "La confirmación por voz no está disponible en este navegador", voiceConfirmHint: "No oí una confirmación clara. Di «sí» para guardar o usa los botones.", readbackIntro: "He entendido:", readbackQuestion: "¿Es correcto?" },
  pt: { panelTitle: "Perguntar ao Dukaandaar", clearMemory: "Limpar a memória temporária", ready: "Pronto para ajudar", welcome: "Olá! Conte o que aconteceu na loja ou pergunte sobre vendas, compras, estoque e despesas.", trySaying: "Experimente dizer", saleSuggestion: "Vendi 5 Maggi por ₹14 cada", restockSuggestion: "O que devo repor?", expenseSuggestion: "Paguei ₹350 de eletricidade", inputPlaceholder: "Digite ou diga o que aconteceu…", voiceInput: "Entrada por voz", shopData: "Os dados da loja ficam aqui", confirmRequired: "Confirme antes de salvar qualquer alteração", enter: "Enter ↵", edit: "Editar", notNow: "Agora não", confirmSave: "Confirmar e salvar", confidenceWarning: "Confira os detalhes com atenção.", saved: "Salvo no livro da loja", saveFailed: "Falha ao salvar", couldNotComplete: "Não foi possível concluir", languageLabel: "Idioma da conversa", openingStock: "Estoque inicial", lossAtCost: "Perda pelo custo", total: "Total", yourAssistant: "Seu assistente de loja", connecting: "Conectando", thinking: "Analisando…", speechProcessing: "Transcrevendo sua gravação…", ttsOn: "Ativar respostas faladas", ttsOff: "Desativar respostas faladas", ttsToggle: "Alternar respostas faladas", ttsUnsupported: "A saída de voz não é compatível", startVoice: "Iniciar entrada por voz", stopVoice: "Parar de ouvir", speakCommand: "Fale um comando", voiceUnsupported: "A entrada por voz requer Chrome ou Edge", sendCommand: "Enviar comando", parserRules: "Analisador por regras · confiança {confidence}%", parserLlm: "Provedor LLM: {provider} · confiança {confidence}%", parserFallback: "Fallback por regras · provedor solicitado: {provider} · confiança {confidence}%", voiceConfirm: "Confirmar por voz", voiceConfirmListening: "Ouvindo… diga sim para salvar", voiceConfirmUnavailable: "A confirmação por voz não está disponível neste navegador", voiceConfirmHint: "Não ouvi uma confirmação clara. Diga “sim” para salvar ou use os botões.", readbackIntro: "Entendi:", readbackQuestion: "Está correto?" },
  ar: { panelTitle: "اسأل دوكاندار", clearMemory: "مسح الذاكرة المؤقتة", ready: "جاهز للمساعدة", welcome: "مرحبًا! أخبرني بما حدث في المتجر أو اسأل عن المبيعات والمشتريات والمخزون والمصروفات.", trySaying: "جرّب أن تقول", saleSuggestion: "بعت ٥ عبوات ماجي بسعر ١٤ روبية للواحدة", restockSuggestion: "ما المنتجات التي تحتاج إلى إعادة طلب؟", expenseSuggestion: "دفعت ٣٥٠ روبية للكهرباء", inputPlaceholder: "اكتب أو قل ما حدث…", voiceInput: "إدخال صوتي", shopData: "تبقى بيانات المتجر هنا", confirmRequired: "التأكيد مطلوب قبل حفظ أي تغيير", enter: "Enter ↵", edit: "تعديل", notNow: "ليس الآن", confirmSave: "تأكيد وحفظ", confidenceWarning: "يرجى مراجعة التفاصيل بعناية.", saved: "تم الحفظ في سجل المتجر", saveFailed: "فشل الحفظ", couldNotComplete: "تعذر الإكمال", languageLabel: "لغة المحادثة", openingStock: "المخزون الافتتاحي", lossAtCost: "الفاقد بالتكلفة", total: "الإجمالي", yourAssistant: "مساعد متجرك", connecting: "جارٍ الاتصال", thinking: "جارٍ التفكير…", speechProcessing: "جارٍ تحويل التسجيل إلى نص…", ttsOn: "تشغيل الردود المنطوقة", ttsOff: "إيقاف الردود المنطوقة", ttsToggle: "تبديل الردود المنطوقة", ttsUnsupported: "الإخراج الصوتي غير مدعوم", startVoice: "بدء الإدخال الصوتي", stopVoice: "إيقاف الاستماع", speakCommand: "انطق أمرًا", voiceUnsupported: "يتطلب الإدخال الصوتي Chrome أو Edge", sendCommand: "إرسال الأمر", parserRules: "محلل القواعد · الثقة {confidence}٪", parserLlm: "مزود LLM: {provider} · الثقة {confidence}٪", parserFallback: "الرجوع إلى القواعد · المزود المطلوب: {provider} · الثقة {confidence}٪", voiceConfirm: "التأكيد صوتيًا", voiceConfirmListening: "جارٍ الاستماع… قل نعم للحفظ", voiceConfirmUnavailable: "التأكيد الصوتي غير متاح في هذا المتصفح", voiceConfirmHint: "لم أسمع تأكيدًا واضحًا. قل نعم للحفظ أو استخدم الأزرار.", readbackIntro: "فهمت:", readbackQuestion: "هل هذا صحيح؟" },
  zh: { panelTitle: "询问 Dukaandaar", clearMemory: "清除短期记忆", ready: "随时为你服务", welcome: "你好！告诉我店里发生了什么，或询问销售、采购、库存和费用。", trySaying: "试着说", saleSuggestion: "售出5包Maggi，每包₹14", restockSuggestion: "哪些商品需要补货？", expenseSuggestion: "支付了₹350电费", inputPlaceholder: "输入或说出发生的事情…", voiceInput: "语音输入", shopData: "店铺数据保留在这里", confirmRequired: "任何写入操作前都需要确认", enter: "Enter ↵", edit: "编辑", notNow: "暂不", confirmSave: "确认并保存", confidenceWarning: "请仔细检查详情。", saved: "已保存到店铺账本", saveFailed: "保存失败", couldNotComplete: "无法完成", languageLabel: "对话语言", openingStock: "期初库存", lossAtCost: "按成本计损耗", total: "总计", yourAssistant: "你的店铺助手", connecting: "正在连接", thinking: "正在思考…", speechProcessing: "正在转写录音…", ttsOn: "开启语音回复", ttsOff: "关闭语音回复", ttsToggle: "切换语音回复", ttsUnsupported: "不支持语音输出", startVoice: "开始语音输入", stopVoice: "停止聆听", speakCommand: "说出指令", voiceUnsupported: "语音输入需要 Chrome 或 Edge", sendCommand: "发送指令", parserRules: "规则解析器 · 置信度 {confidence}%", parserLlm: "LLM 提供方：{provider} · 置信度 {confidence}%", parserFallback: "已回退到规则 · 请求的提供方：{provider} · 置信度 {confidence}%", voiceConfirm: "语音确认", voiceConfirmListening: "正在聆听…说“确认”即可保存", voiceConfirmUnavailable: "此浏览器不支持语音确认", voiceConfirmHint: "没有听到明确确认。请说“确认”保存，或使用按钮。", readbackIntro: "我理解的是：", readbackQuestion: "这样对吗？" },
};

const voiceListeningStatus: Record<ConversationLanguage, string> = {
  en: "Listening · stops after 8 seconds of silence, or tap the mic to stop",
  hi: "सुन रहा हूँ · 8 सेकंड की चुप्पी पर रुकेगा, या माइक दबाकर रोकें",
  bn: "শুনছি · ৮ সেকেন্ড নীরব থাকলে থামবে, অথবা মাইক টিপে থামান",
  fr: "Écoute en cours · arrêt après 8 secondes de silence, ou touchez le micro",
  es: "Escuchando · se detiene tras 8 segundos de silencio, o toca el micrófono",
  pt: "Ouvindo · para após 8 segundos de silêncio, ou toque no microfone",
  ar: "جارٍ الاستماع · يتوقف بعد ٨ ثوانٍ من الصمت، أو اضغط على الميكروفون",
  zh: "正在聆听 · 静音 8 秒后停止，也可点击麦克风停止",
};

const speechProcessingText: Record<ConversationLanguage, string> = {
  en: "Transcribing your recording…",
  hi: "आपकी रिकॉर्डिंग का प्रतिलेखन हो रहा है…",
  bn: "আপনার রেকর্ডিং ট্রান্সক্রাইব করা হচ্ছে…",
  fr: "Transcription de votre enregistrement…",
  es: "Transcribiendo tu grabación…",
  pt: "Transcrevendo sua gravação…",
  ar: "جارٍ تحويل التسجيل إلى نص…",
  zh: "正在转写录音…",
};

const serverSpeechFallbackText: Record<ConversationLanguage, string> = {
  en: "Server transcription failed. Tap the mic and repeat; browser speech recognition will be used.",
  hi: "सर्वर ट्रांसक्रिप्शन विफल हुआ। माइक दबाकर फिर बोलें; ब्राउज़र वाक् पहचान इस्तेमाल होगी।",
  bn: "সার্ভার ট্রান্সক্রিপশন ব্যর্থ হয়েছে। মাইক টিপে আবার বলুন; ব্রাউজারের কথার শনাক্তকরণ ব্যবহার হবে।",
  fr: "La transcription du serveur a échoué. Touchez le micro et répétez ; la reconnaissance vocale du navigateur sera utilisée.",
  es: "Falló la transcripción del servidor. Toca el micrófono y repite; se usará el reconocimiento de voz del navegador.",
  pt: "A transcrição do servidor falhou. Toque no microfone e repita; será usado o reconhecimento de voz do navegador.",
  ar: "فشل تحويل الصوت على الخادم. اضغط على الميكروفون وأعد الكلام؛ سيُستخدم التعرف على الكلام في المتصفح.",
  zh: "服务器转写失败。点击麦克风并重说，将改用浏览器语音识别。",
};

const browserSpeechUnavailableText: Record<ConversationLanguage, string> = {
  en: "Server transcription failed, and browser speech recognition is unavailable. Check your provider setup or type instead.",
  hi: "सर्वर ट्रांसक्रिप्शन विफल हुआ और ब्राउज़र वाक् पहचान उपलब्ध नहीं है। प्रदाता सेटअप जाँचें या लिखें।",
  bn: "সার্ভার ট্রান্সক্রিপশন ব্যর্থ হয়েছে এবং ব্রাউজারের কথার শনাক্তকরণ পাওয়া যাচ্ছে না। প্রোভাইডার সেটআপ দেখুন বা লিখুন।",
  fr: "La transcription du serveur a échoué et la reconnaissance vocale du navigateur est indisponible. Vérifiez la configuration ou saisissez votre texte.",
  es: "Falló la transcripción del servidor y el reconocimiento de voz del navegador no está disponible. Revisa la configuración o escribe.",
  pt: "A transcrição do servidor falhou e o reconhecimento de voz do navegador não está disponível. Confira a configuração ou digite.",
  ar: "فشل تحويل الصوت على الخادم والتعرف على الكلام في المتصفح غير متاح. تحقق من الإعدادات أو اكتب بدلًا من ذلك.",
  zh: "服务器转写失败，且浏览器语音识别不可用。请检查提供商配置或改为输入文字。",
};

export function uiText(language: ConversationLanguage, key: UiKey | "voiceListeningStatus" | "serverSpeechFallback" | "browserSpeechUnavailable"): string {
  if (key === "voiceListeningStatus") return voiceListeningStatus[language] ?? voiceListeningStatus.en;
  if (key === "speechProcessing") return speechProcessingText[language] ?? speechProcessingText.en;
  if (key === "serverSpeechFallback") return serverSpeechFallbackText[language] ?? serverSpeechFallbackText.en;
  if (key === "browserSpeechUnavailable") return browserSpeechUnavailableText[language] ?? browserSpeechUnavailableText.en;
  return ui[language][key] ?? ui.en[key];
}

export const languageOptions: Array<{ code: ConversationLanguage; label: string }> = [
  { code: "en", label: "English" }, { code: "hi", label: "हिन्दी" }, { code: "bn", label: "বাংলা" },
  { code: "fr", label: "Français" }, { code: "es", label: "Español" }, { code: "pt", label: "Português" }, { code: "ar", label: "العربية" }, { code: "zh", label: "中文" },
];

export function speechLocale(language: ConversationLanguage): string {
  const values: Record<ConversationLanguage, string> = { en: "en-IN", hi: "hi-IN", bn: "bn-BD", fr: "fr-FR", es: "es-ES", pt: "pt-BR", ar: "ar-SA", zh: "zh-CN" };
  return values[language];
}

const numberLocales: Record<ConversationLanguage, string> = { en: "en-IN", hi: "hi-IN", bn: "bn-IN", fr: "fr-FR", es: "es-ES", pt: "pt-BR", ar: "ar-SA", zh: "zh-CN" };

export function formatUiCurrency(value: number, language: ConversationLanguage): string {
  return new Intl.NumberFormat(numberLocales[language], { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);
}
