export const CONVERSATION_LANGUAGES = ["en", "hi", "bn", "fr", "es", "pt", "ar", "zh"] as const;
export type ConversationLanguage = typeof CONVERSATION_LANGUAGES[number];

const locales: Record<ConversationLanguage, string> = {
  en: "en-IN", hi: "hi-IN", bn: "bn-IN", fr: "fr-FR", es: "es-ES", pt: "pt-BR", ar: "ar", zh: "zh-CN",
};

const copy = {
  en: {
    unknown: "I can help with sales, purchases, expenses, stock losses, inventory, transaction totals, and history. What would you like to know?",
    product_not_found: "I couldn't find “{product}” in the product catalog.", product_ambiguous: "“{product}” could match {candidates}. Which one did you mean?",
    need_sale_qty: "How many {product} did you sell?", need_purchase_qty: "How many {product} arrived?", need_expense_amount: "How much was the expense?", need_loss_product: "Which product was lost or damaged, and how many units?", multiple_losses: "Please record one product loss at a time so I can confirm the stock impact.", need_product_prices: "I need both a selling price and a cost price to add that product.", ask_period_or_product: "Which period or product should I check?",
    sales_total: "Sales {period}: {amount} across {count} bills.", sales_product: "You sold {qty} × {product} for {amount} {period}.", purchases_total: "Purchases {period}: {amount} across {count} restocks.", expenses_total: "Recorded expenses {period}: {amount} across {count} entries.", losses_total: "Recorded stock losses {period}: {amount} across {count} entries.", profit: "Estimated net profit {period}: {amount}. This subtracts cost of goods sold, expenses, and stock losses.",
    inventory_product: "{product}: {qty} {unit} on hand; {status}.", inventory_summary: "Inventory has {products} products and {units} units total; {low} products are at or below their low-stock threshold.", low_stock: "Items needing a restock: {items}.", no_low_stock: "Nothing is below its low-stock threshold right now.", no_transactions: "No transactions were recorded {period}.", no_sales: "No sales were recorded {period}.", none: "none", all_products: "All products", unit_label: "units", status_out: "out of stock",
    transactions_summary: "{count} transactions {period}: {details}.", history_empty: "No {kind} transactions were found {period}.", history_list: "{kind} history {period} ({count}):\n{lines}", top_products: "Top products sold {period}: {items}.", stock_movement: "{product}: bought {bought}, sold {sold}, lost {lost}; current stock is {current} {unit}.", product_details: "{product}: {qty} {unit} in stock; sell price {sellPrice}, unit cost {costPrice}, stock value {stockValue}; low-stock threshold {threshold}.",
    period_today: "today", period_yesterday: "yesterday", period_week: "this week", period_last_week: "last week", period_month: "this month", period_last_month: "last month", period_all: "all time",
    kind_all: "all", kind_sale: "sales", kind_purchase: "purchases", kind_expense: "expenses", kind_loss: "stock losses", label_sale: "Sale", label_purchase: "Purchase", label_expense: "Expense", label_loss: "Stock loss", status_low: "below the low-stock threshold", status_ok: "stock level is healthy",
    confirm_review: "Review the details below. Nothing is saved until you confirm.", need_sale_price: "What was the selling price?", need_loss_qty: "How many {product} were lost or damaged?", stock_insufficient: "Only {qty} {unit} of {product} are in stock, so I haven't recorded the sale.", stock_effect_sale: "Stock will decrease after you confirm.", stock_effect_purchase: "Stock will increase after you confirm.", initial_purchase_effect: "This initial purchase will be added to purchase history and increase stock once.", stock_effect_loss: "This will reduce available stock and count as a loss at cost.",
    review_sale: "Review sale", review_purchase: "Review purchase", review_expense: "Review expense", review_loss: "Review stock loss", review_product: "Review new product", payment: "Payment: {value}", supplier: "Supplier: {value}", opening_stock: "Opening stock: {qty} {unit} · {category}",
    sale_saved: "Sale recorded for {amount}. Stock has been updated.", purchase_saved: "Purchase recorded for {amount}. Inventory has been updated.", expense_saved: "Expense of {amount} recorded under {category}.", loss_saved: "Loss recorded: {qty} × {product} ({amount} at cost). Stock has been updated.", product_saved: "{product} added to your catalog.", zero_stock_note: "Opening stock is zero: catalog only; no purchase will be recorded.", zero_stock_saved: "Opening stock is zero, so no purchase was recorded.",
    review_product_update: "Review product changes", product_updated: "Updated {product} in your catalog.", product_change: "{field}: {old} → {new}", product_name_conflict: "“{product}” is already used by another catalog item. Choose a different name.", product_stock_unchanged: "Catalog details only; on-hand stock will not change.", product_stock_ledger: "On-hand stock changes only when you record sales, purchases, or losses.", need_product_update: "Tell me what to change: name, category, unit, cost, sell price, or stock-alert threshold.", product_invalid_sell_price: "Sell price must be greater than zero.", price_detail: "Sell {sellPrice} · cost {costPrice}", each: "each", at_cost: "Loss at cost", total: "Total", opening_stock_label: "Opening stock",
  },
  hi: {
    unknown: "मैं बिक्री, खरीद, खर्च, स्टॉक नुकसान, इन्वेंटरी, लेन-देन के कुल और इतिहास में मदद कर सकता हूँ। आप क्या जानना चाहते हैं?",
    product_not_found: "उत्पाद सूची में “{product}” नहीं मिला।", product_ambiguous: "“{product}” से {candidates} में से कौन-सा उत्पाद मतलब है?",
    need_sale_qty: "आपने कितने {product} बेचे?", need_purchase_qty: "कितने {product} आए?", need_expense_amount: "खर्च कितने रुपये का था?", need_loss_product: "किस उत्पाद का कितना नुकसान या खराबी हुई?", multiple_losses: "स्टॉक प्रभाव की पुष्टि के लिए एक बार में एक उत्पाद का नुकसान दर्ज करें।", need_product_prices: "उत्पाद जोड़ने के लिए बिक्री मूल्य और लागत मूल्य दोनों चाहिए।", ask_period_or_product: "कौन-सी अवधि या उत्पाद देखना है?",
    sales_total: "{period} बिक्री {amount} रही ({count} बिल)।", sales_product: "{period} में {product} की {qty} इकाइयाँ {amount} में बिकीं।", purchases_total: "{period} खरीद {amount} रही ({count} बार स्टॉक आया)।", expenses_total: "{period} दर्ज खर्च {amount} है ({count} प्रविष्टियाँ)।", losses_total: "{period} दर्ज स्टॉक नुकसान {amount} है ({count} प्रविष्टियाँ)।", profit: "{period} अनुमानित शुद्ध लाभ {amount} है। इसमें बिक्री की लागत, खर्च और स्टॉक नुकसान घटाए गए हैं।",
    inventory_product: "{product}: {qty} {unit} उपलब्ध; {status}।", inventory_summary: "इन्वेंटरी में {products} उत्पाद और कुल {units} इकाइयाँ हैं; {low} उत्पाद कम-स्टॉक सीमा पर या उससे नीचे हैं।", low_stock: "दोबारा मंगाने योग्य सामान: {items}।", no_low_stock: "अभी कोई उत्पाद कम-स्टॉक सीमा से नीचे नहीं है।", no_transactions: "{period} कोई लेन-देन दर्ज नहीं हुआ।", no_sales: "{period} कोई बिक्री दर्ज नहीं हुई।", none: "कोई नहीं", all_products: "सभी उत्पाद", unit_label: "इकाइयाँ", status_out: "स्टॉक समाप्त है",
    transactions_summary: "{period} कुल {count} लेन-देन: {details}।", history_empty: "{period} {kind} का कोई रिकॉर्ड नहीं मिला।", history_list: "{period} {kind} का इतिहास ({count}):\n{lines}", top_products: "{period} सबसे ज़्यादा बिके उत्पाद: {items}।", stock_movement: "{product}: {bought} खरीदे, {sold} बिके, {lost} नुकसान हुआ; अभी {current} {unit} स्टॉक में हैं।", product_details: "{product}: {qty} {unit} स्टॉक में; बिक्री मूल्य {sellPrice}, लागत {costPrice}, स्टॉक मूल्य {stockValue}; कम-स्टॉक सीमा {threshold}।",
    period_today: "आज", period_yesterday: "कल", period_week: "इस सप्ताह", period_last_week: "पिछले सप्ताह", period_month: "इस महीने", period_last_month: "पिछले महीने", period_all: "अब तक", kind_all: "सभी लेन-देन", kind_sale: "बिक्री", kind_purchase: "खरीद", kind_expense: "खर्च", kind_loss: "स्टॉक नुकसान", label_sale: "बिक्री", label_purchase: "खरीद", label_expense: "खर्च", label_loss: "स्टॉक नुकसान", status_low: "कम-स्टॉक सीमा से नीचे", status_ok: "स्टॉक ठीक है",
    confirm_review: "नीचे दी गई जानकारी जाँचें। पुष्टि करने से पहले कुछ भी सेव नहीं होगा।", need_sale_price: "बिक्री का मूल्य कितना था?", need_loss_qty: "कितने {product} का नुकसान या खराबी हुई?", stock_insufficient: "स्टॉक में केवल {qty} {unit} {product} हैं, इसलिए बिक्री दर्ज नहीं की गई।", stock_effect_sale: "पुष्टि करने के बाद स्टॉक घटेगा।", stock_effect_purchase: "पुष्टि करने के बाद स्टॉक बढ़ेगा।", initial_purchase_effect: "यह शुरुआती खरीद खरीद इतिहास में दर्ज होगी और स्टॉक केवल एक बार बढ़ेगा।", stock_effect_loss: "इससे उपलब्ध स्टॉक घटेगा और लागत पर नुकसान दर्ज होगा।",
    review_sale: "बिक्री की पुष्टि करें", review_purchase: "खरीद की पुष्टि करें", review_expense: "खर्च की पुष्टि करें", review_loss: "स्टॉक नुकसान की पुष्टि करें", review_product: "नए उत्पाद की पुष्टि करें", payment: "भुगतान: {value}", supplier: "आपूर्तिकर्ता: {value}", opening_stock: "शुरुआती स्टॉक: {qty} {unit} · {category}", sale_saved: "{amount} की बिक्री दर्ज हुई। स्टॉक अपडेट कर दिया गया है।", purchase_saved: "{amount} की खरीद दर्ज हुई। इन्वेंटरी अपडेट कर दी गई है।", expense_saved: "{category} के अंतर्गत {amount} का खर्च दर्ज हुआ।", loss_saved: "नुकसान दर्ज हुआ: {qty} × {product} ({amount} लागत पर)। स्टॉक अपडेट कर दिया गया है।", product_saved: "{product} को उत्पाद सूची में जोड़ दिया गया है।", zero_stock_note: "शुरुआती स्टॉक शून्य है: केवल कैटलॉग में जोड़ें; खरीद दर्ज नहीं होगी।", zero_stock_saved: "शुरुआती स्टॉक शून्य था, इसलिए कोई खरीद दर्ज नहीं हुई।", review_product_update: "उत्पाद में बदलाव जाँचें", product_updated: "{product} की जानकारी उत्पाद सूची में अपडेट हुई।", product_change: "{field}: {old} → {new}", product_name_conflict: "“{product}” नाम पहले से किसी दूसरे उत्पाद के लिए इस्तेमाल है। कोई दूसरा नाम चुनें।", product_stock_unchanged: "केवल उत्पाद की जानकारी बदलेगी; मौजूदा स्टॉक नहीं बदलेगा।", product_stock_ledger: "मौजूदा स्टॉक केवल बिक्री, खरीद या नुकसान दर्ज करने पर बदलता है।", need_product_update: "बताइए क्या बदलना है: नाम, श्रेणी, इकाई, लागत, बिक्री मूल्य या स्टॉक अलर्ट सीमा।", product_invalid_sell_price: "बिक्री मूल्य शून्य से अधिक होना चाहिए।", price_detail: "बिक्री {sellPrice} · लागत {costPrice}", each: "प्रति इकाई", at_cost: "लागत पर नुकसान", total: "कुल", opening_stock_label: "शुरुआती स्टॉक",
  },
  bn: {
    unknown: "আমি বিক্রি, কেনাকাটা, খরচ, স্টক ক্ষতি, মজুত, লেনদেনের মোট ও ইতিহাসে সাহায্য করতে পারি। আপনি কী জানতে চান?",
    product_not_found: "পণ্যের তালিকায় “{product}” খুঁজে পাইনি।", product_ambiguous: "“{product}” বলতে {candidates}-এর কোনটি বোঝাচ্ছেন?",
    need_sale_qty: "কতটি {product} বিক্রি হয়েছে?", need_purchase_qty: "কতটি {product} এসেছে?", need_expense_amount: "খরচ কত টাকা হয়েছে?", need_loss_product: "কোন পণ্যের কতটা নষ্ট বা ক্ষতি হয়েছে?", multiple_losses: "স্টকের প্রভাব নিশ্চিত করতে একবারে একটি পণ্যের ক্ষতি নথিভুক্ত করুন।", need_product_prices: "পণ্য যোগ করতে বিক্রয়মূল্য ও ক্রয়মূল্য—দুটিই দরকার।", ask_period_or_product: "কোন সময়কাল বা পণ্যের তথ্য দেখব?",
    sales_total: "{period} বিক্রি {amount} ({count}টি বিল)।", sales_product: "{period} {product} {qty}টি বিক্রি হয়েছে, মোট {amount}।", purchases_total: "{period} কেনাকাটা {amount} ({count}বার স্টক এসেছে)।", expenses_total: "{period} নথিভুক্ত খরচ {amount} ({count}টি এন্ট্রি)।", losses_total: "{period} নথিভুক্ত স্টক ক্ষতি {amount} ({count}টি এন্ট্রি)।", profit: "{period} আনুমানিক নিট লাভ {amount}। এতে বিক্রীত পণ্যের খরচ, খরচের এন্ট্রি ও স্টক ক্ষতি বাদ দেওয়া হয়েছে।",
    inventory_product: "{product}: {qty} {unit} মজুত; {status}।", inventory_summary: "ইনভেন্টরিতে {products}টি পণ্য ও মোট {units}টি ইউনিট আছে; {low}টি পণ্য কম-স্টক সীমায় বা তার নিচে।", low_stock: "আবার অর্ডার করা দরকার: {items}।", no_low_stock: "এখন কোনো পণ্য কম-স্টক সীমার নিচে নেই।", no_transactions: "{period} কোনো লেনদেন নথিভুক্ত হয়নি।", no_sales: "{period} কোনো বিক্রি নথিভুক্ত হয়নি।", none: "কিছুই নেই", all_products: "সব পণ্য", unit_label: "ইউনিট", status_out: "স্টক শেষ",
    transactions_summary: "{period} মোট {count}টি লেনদেন: {details}।", history_empty: "{period} কোনো {kind} রেকর্ড পাওয়া যায়নি।", history_list: "{period} {kind}-এর ইতিহাস ({count}):\n{lines}", top_products: "{period} সবচেয়ে বেশি বিক্রি হওয়া পণ্য: {items}।", stock_movement: "{product}: {bought} কেনা হয়েছে, {sold} বিক্রি হয়েছে, {lost} ক্ষতি হয়েছে; এখন মজুত {current} {unit}।", product_details: "{product}: মজুত {qty} {unit}; বিক্রয়মূল্য {sellPrice}, একক খরচ {costPrice}, মজুতের মূল্য {stockValue}; কম-স্টক সীমা {threshold}।",
    period_today: "আজ", period_yesterday: "গতকাল", period_week: "এই সপ্তাহে", period_last_week: "গত সপ্তাহে", period_month: "এই মাসে", period_last_month: "গত মাসে", period_all: "এখন পর্যন্ত", kind_all: "সব লেনদেন", kind_sale: "বিক্রি", kind_purchase: "কেনাকাটা", kind_expense: "খরচ", kind_loss: "স্টক ক্ষতি", label_sale: "বিক্রি", label_purchase: "কেনাকাটা", label_expense: "খরচ", label_loss: "স্টক ক্ষতি", status_low: "কম-স্টক সীমার নিচে", status_ok: "স্টক ঠিক আছে",
    confirm_review: "নিচের তথ্যগুলো দেখে নিন। নিশ্চিত না করা পর্যন্ত কিছুই সেভ হবে না।", need_sale_price: "বিক্রয়মূল্য কত ছিল?", need_loss_qty: "কতটি {product} নষ্ট বা ক্ষতি হয়েছে?", stock_insufficient: "স্টকে মাত্র {qty} {unit} {product} আছে, তাই বিক্রি নথিভুক্ত করা হয়নি।", stock_effect_sale: "নিশ্চিত করলে স্টক কমবে।", stock_effect_purchase: "নিশ্চিত করলে স্টক বাড়বে।", initial_purchase_effect: "এই প্রাথমিক কেনাকাটা কেনাকাটার ইতিহাসে নথিভুক্ত হবে এবং স্টক একবারই বাড়বে।", stock_effect_loss: "এতে উপলভ্য স্টক কমবে এবং ক্রয়মূল্যে ক্ষতি ধরা হবে।",
    review_sale: "বিক্রি নিশ্চিত করুন", review_purchase: "কেনাকাটা নিশ্চিত করুন", review_expense: "খরচ নিশ্চিত করুন", review_loss: "স্টক ক্ষতি নিশ্চিত করুন", review_product: "নতুন পণ্য নিশ্চিত করুন", payment: "পেমেন্ট: {value}", supplier: "সরবরাহকারী: {value}", opening_stock: "শুরুর মজুত: {qty} {unit} · {category}", sale_saved: "{amount} টাকার বিক্রি নথিভুক্ত হয়েছে। স্টক আপডেট হয়েছে।", purchase_saved: "{amount} টাকার কেনাকাটা নথিভুক্ত হয়েছে। মজুত আপডেট হয়েছে।", expense_saved: "{category} খাতে {amount} খরচ নথিভুক্ত হয়েছে।", loss_saved: "ক্ষতি নথিভুক্ত হয়েছে: {qty} × {product} ({amount} ক্রয়মূল্যে)। স্টক আপডেট হয়েছে।", product_saved: "{product} পণ্যের তালিকায় যোগ হয়েছে।", zero_stock_note: "শুরুর মজুত শূন্য: শুধু পণ্যের তালিকায় যোগ হবে, কোনো কেনাকাটা নথিভুক্ত হবে না।", zero_stock_saved: "শুরুর মজুত শূন্য ছিল, তাই কোনো কেনাকাটা নথিভুক্ত হয়নি।", review_product_update: "পণ্যের পরিবর্তন পর্যালোচনা করুন", product_updated: "{product}-এর তথ্য পণ্যের তালিকায় আপডেট হয়েছে।", product_change: "{field}: {old} → {new}", product_name_conflict: "“{product}” নামটি অন্য একটি পণ্যে আগে থেকেই আছে। অন্য নাম বেছে নিন।", product_stock_unchanged: "শুধু পণ্যের তথ্য বদলাবে; বর্তমান মজুত বদলাবে না।", product_stock_ledger: "বিক্রি, কেনাকাটা বা ক্ষতি নথিভুক্ত করলেই বর্তমান মজুত বদলায়।", need_product_update: "কী বদলাতে হবে বলুন: নাম, বিভাগ, একক, ক্রয়মূল্য, বিক্রয়মূল্য, নাকি স্টক সতর্কতার সীমা।", product_invalid_sell_price: "বিক্রয়মূল্য শূন্যের বেশি হতে হবে।", price_detail: "বিক্রয় {sellPrice} · খরচ {costPrice}", each: "প্রতি ইউনিট", at_cost: "ক্রয়মূল্যে ক্ষতি", total: "মোট", opening_stock_label: "শুরুর মজুত",
  },
  fr: {
    unknown: "Je peux vous aider pour les ventes, achats, dépenses, pertes de stock, inventaire, totaux et historique des transactions. Que voulez-vous savoir ?",
    product_not_found: "Je ne trouve pas « {product} » dans le catalogue.", product_ambiguous: "« {product} » peut désigner {candidates}. Lequel vouliez-vous dire ?",
    need_sale_qty: "Combien de {product} avez-vous vendus ?", need_purchase_qty: "Combien de {product} avez-vous reçus ?", need_expense_amount: "Quel était le montant de la dépense ?", need_loss_product: "Quel produit a été perdu ou abîmé, et en quelle quantité ?", multiple_losses: "Veuillez enregistrer une perte de produit à la fois afin que je puisse vérifier l'effet sur le stock.", need_product_prices: "Il me faut le prix de vente et le coût d'achat pour ajouter ce produit.", ask_period_or_product: "Quelle période ou quel produit dois-je consulter ?",
    sales_total: "Ventes {period} : {amount} pour {count} tickets.", sales_product: "{qty} × {product} vendu(s) pour {amount} {period}.", purchases_total: "Achats {period} : {amount} pour {count} réapprovisionnements.", expenses_total: "Dépenses enregistrées {period} : {amount} dans {count} entrées.", losses_total: "Pertes de stock enregistrées {period} : {amount} dans {count} entrées.", profit: "Bénéfice net estimé {period} : {amount}. Le calcul déduit le coût des marchandises vendues, les dépenses et les pertes de stock.",
    inventory_product: "{product} : {qty} {unit} en stock ; {status}.", inventory_summary: "L'inventaire compte {products} produits et {units} unités ; {low} produits sont au seuil de stock bas ou en dessous.", low_stock: "Produits à réapprovisionner : {items}.", no_low_stock: "Aucun produit n'est actuellement sous le seuil de stock bas.", no_transactions: "Aucune transaction enregistrée {period}.", no_sales: "Aucune vente enregistrée {period}.", none: "aucun", all_products: "Tous les produits", unit_label: "unités", status_out: "rupture de stock",
    transactions_summary: "{count} transactions {period} : {details}.", history_empty: "Aucune transaction de type {kind} trouvée {period}.", history_list: "Historique {kind} {period} ({count}) :\n{lines}", top_products: "Produits les plus vendus {period} : {items}.", stock_movement: "{product} : {bought} achetés, {sold} vendus, {lost} perdus ; stock actuel : {current} {unit}.", product_details: "{product} : {qty} {unit} en stock ; prix de vente {sellPrice}, coût unitaire {costPrice}, valeur du stock {stockValue} ; seuil bas {threshold}.",
    period_today: "aujourd'hui", period_yesterday: "hier", period_week: "cette semaine", period_last_week: "la semaine dernière", period_month: "ce mois-ci", period_last_month: "le mois dernier", period_all: "depuis le début", kind_all: "toutes", kind_sale: "ventes", kind_purchase: "achats", kind_expense: "dépenses", kind_loss: "pertes de stock", label_sale: "Vente", label_purchase: "Achat", label_expense: "Dépense", label_loss: "Perte de stock", status_low: "sous le seuil de stock bas", status_ok: "stock suffisant",
    confirm_review: "Vérifiez les détails ci-dessous. Rien ne sera enregistré avant votre confirmation.", need_sale_price: "Quel était le prix de vente ?", need_loss_qty: "Combien de {product} ont été perdus ou abîmés ?", stock_insufficient: "Il ne reste que {qty} {unit} de {product} ; la vente n'a pas été enregistrée.", stock_effect_sale: "Le stock diminuera après confirmation.", stock_effect_purchase: "Le stock augmentera après confirmation.", initial_purchase_effect: "Cet achat initial sera ajouté à l’historique des achats et augmentera le stock une seule fois.", stock_effect_loss: "Le stock disponible diminuera et la perte sera évaluée au coût d'achat.",
    review_sale: "Vérifier la vente", review_purchase: "Vérifier l'achat", review_expense: "Vérifier la dépense", review_loss: "Vérifier la perte de stock", review_product: "Vérifier le nouveau produit", payment: "Paiement : {value}", supplier: "Fournisseur : {value}", opening_stock: "Stock initial : {qty} {unit} · {category}", sale_saved: "Vente de {amount} enregistrée. Le stock a été mis à jour.", purchase_saved: "Achat de {amount} enregistré. L'inventaire a été mis à jour.", expense_saved: "Dépense de {amount} enregistrée dans la catégorie {category}.", loss_saved: "Perte enregistrée : {qty} × {product} ({amount} au coût d'achat). Le stock a été mis à jour.", product_saved: "{product} a été ajouté au catalogue.", zero_stock_note: "Le stock initial est nul : le produit sera ajouté au catalogue sans enregistrer d’achat.", zero_stock_saved: "Le stock initial était nul ; aucun achat n’a été enregistré.", review_product_update: "Vérifier les modifications du produit", product_updated: "Les informations de {product} ont été mises à jour.", product_change: "{field} : {old} → {new}", product_name_conflict: "« {product} » est déjà utilisé par un autre produit. Choisissez un autre nom.", product_stock_unchanged: "Seules les informations du produit changent ; le stock actuel reste inchangé.", product_stock_ledger: "Le stock actuel ne change qu’avec les ventes, achats ou pertes enregistrés.", need_product_update: "Indiquez ce qu’il faut modifier : nom, catégorie, unité, coût, prix de vente ou seuil d’alerte de stock.", product_invalid_sell_price: "Le prix de vente doit être supérieur à zéro.", price_detail: "Vente {sellPrice} · coût {costPrice}", each: "l'unité", at_cost: "Perte au coût d'achat", total: "Total", opening_stock_label: "Stock initial",
  },
  es: {
    unknown: "Puedo ayudarte con ventas, compras, gastos, pérdidas de stock, inventario, totales e historial de transacciones. ¿Qué quieres saber?",
    product_not_found: "No encuentro “{product}” en el catálogo.", product_ambiguous: "“{product}” podría ser {candidates}. ¿Cuál querías decir?",
    need_sale_qty: "¿Cuántos {product} vendiste?", need_purchase_qty: "¿Cuántos {product} llegaron?", need_expense_amount: "¿Cuál fue el importe del gasto?", need_loss_product: "¿Qué producto se perdió o dañó y en qué cantidad?", multiple_losses: "Registra una pérdida de producto a la vez para confirmar el efecto en el inventario.", need_product_prices: "Necesito el precio de venta y el coste para añadir ese producto.", ask_period_or_product: "¿Qué período o producto quieres consultar?",
    sales_total: "Ventas {period}: {amount} en {count} tickets.", sales_product: "Vendiste {qty} × {product} por {amount} {period}.", purchases_total: "Compras {period}: {amount} en {count} reposiciones.", expenses_total: "Gastos registrados {period}: {amount} en {count} apuntes.", losses_total: "Pérdidas de stock registradas {period}: {amount} en {count} apuntes.", profit: "Beneficio neto estimado {period}: {amount}. Se descuentan el coste de los productos vendidos, los gastos y las pérdidas de stock.",
    inventory_product: "{product}: {qty} {unit} disponibles; {status}.", inventory_summary: "El inventario tiene {products} productos y {units} unidades; {low} productos están en el umbral de stock bajo o por debajo.", low_stock: "Productos que necesitan reposición: {items}.", no_low_stock: "Ningún producto está por debajo del umbral de stock bajo.", no_transactions: "No hay transacciones registradas {period}.", no_sales: "No hay ventas registradas {period}.", none: "ninguno", all_products: "Todos los productos", unit_label: "unidades", status_out: "sin existencias",
    transactions_summary: "{count} transacciones {period}: {details}.", history_empty: "No se encontraron transacciones de tipo {kind} {period}.", history_list: "Historial de {kind} {period} ({count}):\n{lines}", top_products: "Productos más vendidos {period}: {items}.", stock_movement: "{product}: comprados {bought}, vendidos {sold}, perdidos {lost}; stock actual {current} {unit}.", product_details: "{product}: {qty} {unit} en stock; precio de venta {sellPrice}, coste unitario {costPrice}, valor del stock {stockValue}; umbral de stock bajo {threshold}.",
    period_today: "hoy", period_yesterday: "ayer", period_week: "esta semana", period_last_week: "la semana pasada", period_month: "este mes", period_last_month: "el mes pasado", period_all: "en total", kind_all: "todas", kind_sale: "ventas", kind_purchase: "compras", kind_expense: "gastos", kind_loss: "pérdidas de stock", label_sale: "Venta", label_purchase: "Compra", label_expense: "Gasto", label_loss: "Pérdida de stock", status_low: "por debajo del umbral de stock bajo", status_ok: "nivel de stock correcto",
    confirm_review: "Revisa los detalles. No se guardará nada hasta que confirmes.", need_sale_price: "¿Cuál fue el precio de venta?", need_loss_qty: "¿Cuántos {product} se perdieron o dañaron?", stock_insufficient: "Solo quedan {qty} {unit} de {product}; no he registrado la venta.", stock_effect_sale: "El stock disminuirá al confirmar.", stock_effect_purchase: "El stock aumentará al confirmar.", initial_purchase_effect: "Esta compra inicial se añadirá al historial de compras y el stock aumentará una sola vez.", stock_effect_loss: "El stock disponible disminuirá y la pérdida se valorará al coste.",
    review_sale: "Revisar venta", review_purchase: "Revisar compra", review_expense: "Revisar gasto", review_loss: "Revisar pérdida de stock", review_product: "Revisar producto nuevo", payment: "Pago: {value}", supplier: "Proveedor: {value}", opening_stock: "Stock inicial: {qty} {unit} · {category}", sale_saved: "Venta de {amount} registrada. El stock se ha actualizado.", purchase_saved: "Compra de {amount} registrada. El inventario se ha actualizado.", expense_saved: "Gasto de {amount} registrado en {category}.", loss_saved: "Pérdida registrada: {qty} × {product} ({amount} al coste). El stock se ha actualizado.", product_saved: "{product} añadido al catálogo.", zero_stock_note: "El stock inicial es cero: solo se añadirá al catálogo, sin registrar una compra.", zero_stock_saved: "El stock inicial era cero, así que no se registró ninguna compra.", review_product_update: "Revisar cambios del producto", product_updated: "Se actualizaron los datos de {product}.", product_change: "{field}: {old} → {new}", product_name_conflict: "“{product}” ya se usa en otro producto. Elige otro nombre.", product_stock_unchanged: "Solo cambiarán los datos del producto; el stock actual no cambiará.", product_stock_ledger: "El stock actual solo cambia al registrar ventas, compras o pérdidas.", need_product_update: "Indica qué quieres cambiar: nombre, categoría, unidad, coste, precio de venta o umbral de alerta.", product_invalid_sell_price: "El precio de venta debe ser mayor que cero.", price_detail: "Venta {sellPrice} · coste {costPrice}", each: "cada unidad", at_cost: "Pérdida al coste", total: "Total", opening_stock_label: "Stock inicial",
  },
  pt: {
    unknown: "Posso ajudar com vendas, compras, despesas, perdas de estoque, inventário, totais e histórico de transações. O que você quer saber?",
    product_not_found: "Não encontrei “{product}” no catálogo.", product_ambiguous: "“{product}” pode corresponder a {candidates}. Qual deles você quis dizer?",
    need_sale_qty: "Quantos {product} você vendeu?", need_purchase_qty: "Quantos {product} chegaram?", need_expense_amount: "Qual foi o valor da despesa?", need_loss_product: "Qual produto foi perdido ou danificado, e em que quantidade?", multiple_losses: "Registre uma perda de produto por vez para confirmar o impacto no estoque.", need_product_prices: "Preciso do preço de venda e do custo para adicionar esse produto.", ask_period_or_product: "Qual período ou produto devo consultar?",
    sales_total: "Vendas {period}: {amount} em {count} cupons.", sales_product: "Você vendeu {qty} × {product} por {amount} {period}.", purchases_total: "Compras {period}: {amount} em {count} reposições.", expenses_total: "Despesas registradas {period}: {amount} em {count} lançamentos.", losses_total: "Perdas de estoque registradas {period}: {amount} em {count} lançamentos.", profit: "Lucro líquido estimado {period}: {amount}. O cálculo desconta o custo dos produtos vendidos, as despesas e as perdas de estoque.",
    inventory_product: "{product}: {qty} {unit} disponíveis; {status}.", inventory_summary: "O inventário tem {products} produtos e {units} unidades; {low} produtos estão no limite de estoque baixo ou abaixo dele.", low_stock: "Itens que precisam de reposição: {items}.", no_low_stock: "Nenhum produto está abaixo do limite de estoque baixo.", no_transactions: "Nenhuma transação registrada {period}.", no_sales: "Nenhuma venda registrada {period}.", none: "nenhum", all_products: "Todos os produtos", unit_label: "unidades", status_out: "sem estoque",
    transactions_summary: "{count} transações {period}: {details}.", history_empty: "Nenhuma transação do tipo {kind} encontrada {period}.", history_list: "Histórico de {kind} {period} ({count}):\n{lines}", top_products: "Produtos mais vendidos {period}: {items}.", stock_movement: "{product}: comprados {bought}, vendidos {sold}, perdidos {lost}; estoque atual {current} {unit}.", product_details: "{product}: {qty} {unit} em estoque; preço de venda {sellPrice}, custo unitário {costPrice}, valor do estoque {stockValue}; limite de estoque baixo {threshold}.",
    period_today: "hoje", period_yesterday: "ontem", period_week: "esta semana", period_last_week: "semana passada", period_month: "este mês", period_last_month: "mês passado", period_all: "no total", kind_all: "todas", kind_sale: "vendas", kind_purchase: "compras", kind_expense: "despesas", kind_loss: "perdas de estoque", label_sale: "Venda", label_purchase: "Compra", label_expense: "Despesa", label_loss: "Perda de estoque", status_low: "abaixo do limite de estoque baixo", status_ok: "nível de estoque adequado",
    confirm_review: "Confira os detalhes abaixo. Nada será salvo até você confirmar.", need_sale_price: "Qual foi o preço de venda?", need_loss_qty: "Quantos {product} foram perdidos ou danificados?", stock_insufficient: "Há apenas {qty} {unit} de {product} em estoque; a venda não foi registrada.", stock_effect_sale: "O estoque diminuirá após a confirmação.", stock_effect_purchase: "O estoque aumentará após a confirmação.", initial_purchase_effect: "Esta compra inicial será registrada no histórico de compras e aumentará o estoque uma única vez.", stock_effect_loss: "O estoque disponível diminuirá e a perda será avaliada pelo custo.",
    review_sale: "Revisar venda", review_purchase: "Revisar compra", review_expense: "Revisar despesa", review_loss: "Revisar perda de estoque", review_product: "Revisar novo produto", payment: "Pagamento: {value}", supplier: "Fornecedor: {value}", opening_stock: "Estoque inicial: {qty} {unit} · {category}", sale_saved: "Venda de {amount} registrada. O estoque foi atualizado.", purchase_saved: "Compra de {amount} registrada. O inventário foi atualizado.", expense_saved: "Despesa de {amount} registrada em {category}.", loss_saved: "Perda registrada: {qty} × {product} ({amount} ao custo). O estoque foi atualizado.", product_saved: "{product} foi adicionado ao catálogo.", zero_stock_note: "O estoque inicial é zero: o produto será adicionado apenas ao catálogo, sem registrar uma compra.", zero_stock_saved: "O estoque inicial era zero, então nenhuma compra foi registrada.", review_product_update: "Revisar alterações do produto", product_updated: "Os dados de {product} foram atualizados.", product_change: "{field}: {old} → {new}", product_name_conflict: "“{product}” já é usado por outro produto. Escolha outro nome.", product_stock_unchanged: "Só os dados do produto serão alterados; o estoque atual não muda.", product_stock_ledger: "O estoque atual só muda ao registrar vendas, compras ou perdas.", need_product_update: "Diga o que deseja alterar: nome, categoria, unidade, custo, preço de venda ou limite de alerta.", product_invalid_sell_price: "O preço de venda deve ser maior que zero.", price_detail: "Venda {sellPrice} · custo {costPrice}", each: "cada unidade", at_cost: "Perda pelo custo", total: "Total", opening_stock_label: "Estoque inicial",
  },
  ar: {
    unknown: "يمكنني مساعدتك في المبيعات والمشتريات والمصروفات وفاقد المخزون والجرد وإجماليات المعاملات وسجلها. ماذا تريد أن تعرف؟",
    product_not_found: "لم أجد «{product}» في قائمة المنتجات.", product_ambiguous: "قد تشير «{product}» إلى {candidates}. أي منتج تقصد؟",
    need_sale_qty: "كم وحدة من {product} بعت؟", need_purchase_qty: "كم وحدة من {product} وصلت؟", need_expense_amount: "ما قيمة المصروف؟", need_loss_product: "ما المنتج الذي فُقد أو تلف، وما الكمية؟", multiple_losses: "سجّل فاقد منتج واحد في كل مرة حتى أتحقق من أثره على المخزون.", need_product_prices: "أحتاج إلى سعر البيع وسعر التكلفة لإضافة هذا المنتج.", ask_period_or_product: "ما الفترة أو المنتج الذي تريد مراجعته؟",
    sales_total: "المبيعات {period}: {amount} عبر {count} فواتير.", sales_product: "بعت {qty} × {product} بمبلغ {amount} {period}.", purchases_total: "المشتريات {period}: {amount} عبر {count} عمليات توريد.", expenses_total: "المصروفات المسجلة {period}: {amount} عبر {count} قيود.", losses_total: "فاقد المخزون المسجل {period}: {amount} عبر {count} قيود.", profit: "صافي الربح التقديري {period}: {amount}. يُخصم منه تكلفة البضاعة المباعة والمصروفات وفاقد المخزون.",
    inventory_product: "{product}: المتاح {qty} {unit}؛ {status}.", inventory_summary: "يضم المخزون {products} منتجات و{units} وحدات؛ {low} منتجات عند حد المخزون المنخفض أو دونه.", low_stock: "المنتجات التي تحتاج إلى إعادة طلب: {items}.", no_low_stock: "لا توجد منتجات حاليًا دون حد المخزون المنخفض.", no_transactions: "لم تُسجّل أي معاملات {period}.", no_sales: "لم تُسجّل أي مبيعات {period}.", none: "لا شيء", all_products: "كل المنتجات", unit_label: "وحدات", status_out: "نفد المخزون",
    transactions_summary: "عدد المعاملات {period}: {count} — {details}.", history_empty: "لم يتم العثور على {kind} {period}.", history_list: "سجل {kind} {period} ({count}):\n{lines}", top_products: "أكثر المنتجات مبيعًا {period}: {items}.", stock_movement: "{product}: تم شراء {bought} وبيع {sold} وفقد {lost}؛ المخزون الحالي {current} {unit}.", product_details: "{product}: في المخزون {qty} {unit}؛ سعر البيع {sellPrice}، تكلفة الوحدة {costPrice}، قيمة المخزون {stockValue}؛ حد المخزون المنخفض {threshold}.",
    period_today: "اليوم", period_yesterday: "أمس", period_week: "هذا الأسبوع", period_last_week: "الأسبوع الماضي", period_month: "هذا الشهر", period_last_month: "الشهر الماضي", period_all: "الإجمالي", kind_all: "كل المعاملات", kind_sale: "المبيعات", kind_purchase: "المشتريات", kind_expense: "المصروفات", kind_loss: "فاقد المخزون", label_sale: "بيع", label_purchase: "شراء", label_expense: "مصروف", label_loss: "فاقد مخزون", status_low: "أقل من حد المخزون المنخفض", status_ok: "مستوى المخزون جيد",
    confirm_review: "راجع التفاصيل أدناه. لن يُحفظ أي شيء حتى تؤكد.", need_sale_price: "ما سعر البيع؟", need_loss_qty: "كم وحدة من {product} فُقدت أو تلفت؟", stock_insufficient: "المتوفر فقط {qty} {unit} من {product}، لذلك لم أسجل البيع.", stock_effect_sale: "سينخفض المخزون بعد التأكيد.", stock_effect_purchase: "سيزداد المخزون بعد التأكيد.", initial_purchase_effect: "سيُضاف هذا الشراء الأولي إلى سجل المشتريات وسيزيد المخزون مرة واحدة فقط.", stock_effect_loss: "سيقل المخزون المتاح وسيُحسب الفاقد بالتكلفة.",
    review_sale: "مراجعة البيع", review_purchase: "مراجعة الشراء", review_expense: "مراجعة المصروف", review_loss: "مراجعة فاقد المخزون", review_product: "مراجعة المنتج الجديد", payment: "الدفع: {value}", supplier: "المورّد: {value}", opening_stock: "المخزون الافتتاحي: {qty} {unit} · {category}", sale_saved: "تم تسجيل بيع بقيمة {amount}. تم تحديث المخزون.", purchase_saved: "تم تسجيل شراء بقيمة {amount}. تم تحديث المخزون.", expense_saved: "تم تسجيل مصروف {amount} ضمن {category}.", loss_saved: "تم تسجيل الفاقد: {qty} × {product} ({amount} بالتكلفة). تم تحديث المخزون.", product_saved: "تمت إضافة {product} إلى قائمة المنتجات.", zero_stock_note: "المخزون الافتتاحي صفر: ستتم إضافة المنتج إلى القائمة فقط دون تسجيل أي عملية شراء.", zero_stock_saved: "كان المخزون الافتتاحي صفرًا، لذلك لم يتم تسجيل أي عملية شراء.", review_product_update: "مراجعة تغييرات المنتج", product_updated: "تم تحديث بيانات {product}.", product_change: "{field}: {old} → {new}", product_name_conflict: "الاسم «{product}» مستخدم بالفعل لمنتج آخر. اختر اسمًا مختلفًا.", product_stock_unchanged: "ستتغير بيانات المنتج فقط؛ لن يتغير المخزون الحالي.", product_stock_ledger: "يتغير المخزون الحالي فقط عند تسجيل المبيعات أو المشتريات أو الفاقد.", need_product_update: "أخبرني بما تريد تغييره: الاسم أو الفئة أو الوحدة أو التكلفة أو سعر البيع أو حد تنبيه المخزون.", product_invalid_sell_price: "يجب أن يكون سعر البيع أكبر من صفر.", price_detail: "بيع {sellPrice} · تكلفة {costPrice}", each: "للوحدة", at_cost: "الفاقد بالتكلفة", total: "الإجمالي", opening_stock_label: "المخزون الافتتاحي",
  },
  zh: {
    unknown: "我可以帮你查询销售、采购、费用、库存损耗、库存、交易总数和交易记录。你想了解什么？",
    product_not_found: "商品目录中没有找到“{product}”。", product_ambiguous: "“{product}”可能是{candidates}中的一个。你指的是哪一个？",
    need_sale_qty: "卖出了多少件{product}？", need_purchase_qty: "收到了多少件{product}？", need_expense_amount: "这笔费用是多少？", need_loss_product: "哪种商品损坏或丢失了，数量是多少？", multiple_losses: "请一次记录一种商品损耗，以便确认库存变化。", need_product_prices: "添加商品需要提供售价和成本价。", ask_period_or_product: "你想查询哪个时间段或哪种商品？",
    sales_total: "{period}销售额为{amount}，共{count}笔销售。", sales_product: "{period}售出{qty}件{product}，金额为{amount}。", purchases_total: "{period}采购金额为{amount}，共{count}次进货。", expenses_total: "{period}已记录费用为{amount}，共{count}笔。", losses_total: "{period}已记录库存损耗为{amount}，共{count}笔。", profit: "{period}预计净利润为{amount}。已扣除售出商品成本、费用和库存损耗。",
    inventory_product: "{product}：库存{qty}{unit}；{status}。", inventory_summary: "库存共有{products}种商品、{units}件；其中{low}种达到或低于低库存阈值。", low_stock: "需要补货的商品：{items}。", no_low_stock: "目前没有商品低于低库存阈值。", no_transactions: "{period}没有记录交易。", no_sales: "{period}没有记录销售。", none: "无", all_products: "全部商品", unit_label: "件", status_out: "库存已售罄",
    transactions_summary: "{period}共{count}笔交易：{details}。", history_empty: "{period}没有找到{kind}记录。", history_list: "{period}{kind}记录（{count}笔）：\n{lines}", top_products: "{period}销量最高的商品：{items}。", stock_movement: "{product}：进货{bought}件，售出{sold}件，损耗{lost}件；当前库存{current}{unit}。", product_details: "{product}：库存{qty}{unit}；售价{sellPrice}，单位成本{costPrice}，库存价值{stockValue}；低库存阈值{threshold}。",
    period_today: "今天", period_yesterday: "昨天", period_week: "本周", period_last_week: "上周", period_month: "本月", period_last_month: "上个月", period_all: "全部时间", kind_all: "全部交易", kind_sale: "销售", kind_purchase: "采购", kind_expense: "费用", kind_loss: "库存损耗", label_sale: "销售", label_purchase: "采购", label_expense: "费用", label_loss: "库存损耗", status_low: "低于低库存阈值", status_ok: "库存充足",
    confirm_review: "请检查以下详情。确认前不会保存任何内容。", need_sale_price: "售价是多少？", need_loss_qty: "丢失或损坏了多少件{product}？", stock_insufficient: "{product}库存只有{qty}{unit}，因此没有记录这笔销售。", stock_effect_sale: "确认后库存会减少。", stock_effect_purchase: "确认后库存会增加。", initial_purchase_effect: "这笔首次采购将记入采购历史，库存只增加一次。", stock_effect_loss: "确认后可用库存会减少，并按成本计入损耗。",
    review_sale: "确认销售", review_purchase: "确认采购", review_expense: "确认费用", review_loss: "确认库存损耗", review_product: "确认新商品", payment: "付款方式：{value}", supplier: "供应商：{value}", opening_stock: "期初库存：{qty}{unit} · {category}", sale_saved: "已记录{amount}的销售，库存已更新。", purchase_saved: "已记录{amount}的采购，库存已更新。", expense_saved: "已记录{category}费用{amount}。", loss_saved: "已记录损耗：{qty} × {product}（成本{amount}）。库存已更新。", product_saved: "已将{product}添加到商品目录。", zero_stock_note: "期初库存为零：只添加到商品目录，不会记录采购。", zero_stock_saved: "期初库存为零，因此没有记录采购。", review_product_update: "检查商品更改", product_updated: "已更新{product}的商品信息。", product_change: "{field}：{old} → {new}", product_name_conflict: "“{product}”已被其他商品使用，请选择其他名称。", product_stock_unchanged: "只更改商品资料，不更改当前库存。", product_stock_ledger: "只有记录销售、采购或损耗时，当前库存才会变化。", need_product_update: "请说明要更改什么：名称、类别、单位、成本价、售价或库存提醒阈值。", product_invalid_sell_price: "售价必须大于零。", price_detail: "售价{sellPrice} · 成本{costPrice}", each: "每件", at_cost: "按成本计损耗", total: "总计", opening_stock_label: "期初库存",
  },
} as const;

export type PhraseKey = keyof typeof copy.en;

export function isConversationLanguage(value: unknown): value is ConversationLanguage {
  return typeof value === "string" && (CONVERSATION_LANGUAGES as readonly string[]).includes(value);
}

export function detectLanguage(text: string): ConversationLanguage {
  if (/\p{Script=Bengali}/u.test(text)) return "bn";
  if (/\p{Script=Devanagari}/u.test(text)) return "hi";
  if (/\p{Script=Arabic}/u.test(text)) return "ar";
  if (/\p{Script=Han}/u.test(text)) return "zh";
  const lower = text.normalize("NFKC").toLocaleLowerCase();
  const hasAny = (words: string[]) => words.some((word) => lower.includes(word));
  if (hasAny(["bonjour", "combien", "ventes", "achats", "dépense", "perte", "bénéfice", "aujourd'hui", "historique", "semaine", "hier", "cinq", "je ", "j'ai", "vendu", "acheté", "payé", "enregistré", "crée", "créer", "ajoute", "ajouter", "produit"])) return "fr";
  if (hasAny(["olá", "ola", "quanto", "vendas", "despesa", "despesas", "perda", "perdas", "lucro", "hoje", "histórico", "ontem", "estoque", "você", "quero", "comprei", "comprou", "paguei", "perdi", "eletricidade", "adicionar", "adicione", "criar", "crie", "produto"])) return "pt";
  if (hasAny(["hola", "cuánto", "cuanto", "ventas", "compras", "gastos", "pérdida", "ganancia", "hoy", "historial", "ayer", "inventario", "cuál", "qué", "electricidad", "vendí", "compré", "pagué", "perdí", "perdió", "añade", "agrega", "producto", "crear"])) return "es";
  return "en";
}

export function localizedMessage(language: ConversationLanguage, key: PhraseKey, values: Record<string, string | number> = {}): string {
  const template: string = copy[language][key] ?? copy.en[key];
  return template.replace(/\{([A-Za-z]+)\}/g, (_match, name: string) => String(values[name] ?? ""));
}

export function localizedPeriod(language: ConversationLanguage, period: string): string {
  const key = `period_${period}` as PhraseKey;
  return localizedMessage(language, key);
}

export function localizedKind(language: ConversationLanguage, kind: string): string {
  const key = `kind_${kind}` as PhraseKey;
  return localizedMessage(language, key);
}

export function transactionKindLabel(language: ConversationLanguage, kind: "sale" | "purchase" | "expense" | "loss"): string {
  const key = `label_${kind}` as PhraseKey;
  return localizedMessage(language, key);
}

export function categoryLabel(language: ConversationLanguage, category: string): string {
  const labels: Record<ConversationLanguage, Record<string, string>> = {
    en: { rent: "rent", electricity: "electricity", transport: "transport", staff: "staff", misc: "miscellaneous" },
    hi: { rent: "किराया", electricity: "बिजली", transport: "परिवहन", staff: "कर्मचारी", misc: "अन्य" },
    bn: { rent: "ভাড়া", electricity: "বিদ্যুৎ", transport: "পরিবহন", staff: "কর্মী", misc: "অন্যান্য" },
    fr: { rent: "loyer", electricity: "électricité", transport: "transport", staff: "personnel", misc: "divers" },
    es: { rent: "alquiler", electricity: "electricidad", transport: "transporte", staff: "personal", misc: "varios" },
    pt: { rent: "aluguel", electricity: "eletricidade", transport: "transporte", staff: "equipe", misc: "diversos" },
    ar: { rent: "الإيجار", electricity: "الكهرباء", transport: "النقل", staff: "الموظفون", misc: "متفرقات" },
    zh: { rent: "租金", electricity: "电费", transport: "运输", staff: "员工", misc: "其他" },
  };
  return labels[language][category] ?? category;
}

export function paymentMethodLabel(language: ConversationLanguage, method: string): string {
  const labels: Record<ConversationLanguage, Record<string, string>> = {
    en: { cash: "cash", upi: "UPI", credit: "credit" }, hi: { cash: "नकद", upi: "UPI", credit: "उधार" }, bn: { cash: "নগদ", upi: "UPI", credit: "বাকি" },
    fr: { cash: "espèces", upi: "UPI", credit: "crédit" }, es: { cash: "efectivo", upi: "UPI", credit: "crédito" }, pt: { cash: "dinheiro", upi: "UPI", credit: "crédito" },
    ar: { cash: "نقدًا", upi: "UPI", credit: "آجل" }, zh: { cash: "现金", upi: "UPI", credit: "赊账" },
  };
  return labels[language][method] ?? method;
}

export type ProductFieldKey = "name" | "aliases" | "category" | "unit" | "costPrice" | "sellPrice" | "lowStockThreshold";

export function productFieldLabel(language: ConversationLanguage, field: ProductFieldKey): string {
  const labels: Record<ConversationLanguage, Record<ProductFieldKey, string>> = {
    en: { name: "Name", aliases: "Aliases", category: "Category", unit: "Unit", costPrice: "Cost price", sellPrice: "Sell price", lowStockThreshold: "Stock alert at" },
    hi: { name: "नाम", aliases: "उपनाम", category: "श्रेणी", unit: "इकाई", costPrice: "लागत मूल्य", sellPrice: "बिक्री मूल्य", lowStockThreshold: "स्टॉक अलर्ट सीमा" },
    bn: { name: "নাম", aliases: "বিকল্প নাম", category: "বিভাগ", unit: "একক", costPrice: "ক্রয়মূল্য", sellPrice: "বিক্রয়মূল্য", lowStockThreshold: "স্টক সতর্কতার সীমা" },
    fr: { name: "Nom", aliases: "Alias", category: "Catégorie", unit: "Unité", costPrice: "Coût unitaire", sellPrice: "Prix de vente", lowStockThreshold: "Seuil d'alerte de stock" },
    es: { name: "Nombre", aliases: "Alias", category: "Categoría", unit: "Unidad", costPrice: "Coste", sellPrice: "Precio de venta", lowStockThreshold: "Umbral de alerta" },
    pt: { name: "Nome", aliases: "Apelidos", category: "Categoria", unit: "Unidade", costPrice: "Custo", sellPrice: "Preço de venda", lowStockThreshold: "Limite de alerta" },
    ar: { name: "الاسم", aliases: "الأسماء البديلة", category: "الفئة", unit: "الوحدة", costPrice: "سعر التكلفة", sellPrice: "سعر البيع", lowStockThreshold: "حد تنبيه المخزون" },
    zh: { name: "名称", aliases: "别名", category: "类别", unit: "单位", costPrice: "成本价", sellPrice: "售价", lowStockThreshold: "库存提醒阈值" },
  };
  return labels[language][field];
}

export function formatLocalizedNumber(value: number, language: ConversationLanguage): string {
  return new Intl.NumberFormat(locales[language], { maximumFractionDigits: 2 }).format(value);
}

export function formatLocalizedCurrency(value: number, language: ConversationLanguage): string {
  return new Intl.NumberFormat(locales[language], { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);
}

export function formatLocalizedDate(value: string, language: ConversationLanguage): string {
  return new Intl.DateTimeFormat(locales[language], { day: "numeric", month: "short", year: "numeric", timeZone: "Asia/Kolkata" }).format(new Date(value));
}
